export const HTTP_FLOW_LIVE_DIRECT_MIN_INTERVAL_MS = 100
export const HTTP_FLOW_LIVE_DIRECT_SUSTAINED_INTERVAL_MS = 100
export const HTTP_FLOW_LIVE_DIRECT_SUSTAINED_PENDING_ROWS = 8
export const MITM_FLOW_TABLE_OVERSCAN = 2
