export type ChatDataStoreKey =
  | 'aiChatDataStore'
  | 'knowledgeBaseDataStore'
  | 'histroyAiStore'
  | 'FlowAiStore'
  | 'irifyAiCodeAuditPageAiStore'
  | 'irifyRuleGenPageAiStore'
  | 'yakRunnerPageAiStore'
  | 'browserExtensionAiStore'
  | 'WebFuzzerAiStore'
  | 'unknown'
