/** @name 图标对应关系(yak-runner文件树) */
export const KeyToIcon: Record<string, {iconPath: string}> = {
    _file: {iconPath: "./icons/file.svg"},
    _fd_default: {iconPath: "./icons/folders/default.svg"},
    "_fd_default-open": {iconPath: "./icons/folders/default-open.svg"},
    _fd_root: {iconPath: "./icons/folders/root.svg"},
    "_fd_root-open": {iconPath: "./icons/folders/root-open.svg"},
    _fd_node: {iconPath: "./icons/folders/node.svg"},
    "_fd_node-open": {iconPath: "./icons/folders/node-open.svg"},
    _fd_bower: {iconPath: "./icons/folders/bower.svg"},
    "_fd_bower-open": {iconPath: "./icons/folders/bower-open.svg"},
    _fd_git: {iconPath: "./icons/folders/git.svg"},
    "_fd_git-open": {iconPath: "./icons/folders/git-open.svg"},
    _fd_tests: {iconPath: "./icons/folders/tests.svg"},
    "_fd_tests-open": {iconPath: "./icons/folders/tests-open.svg"},
    _fd_vscode: {iconPath: "./icons/folders/vsc.svg"},
    "_fd_vscode-open": {iconPath: "./icons/folders/vsc-open.svg"},
    _fd_jest: {iconPath: "./icons/folders/jest.svg"},
    "_fd_jest-open": {iconPath: "./icons/folders/jest-open.svg"},
    _fd_build: {iconPath: "./icons/folders/build.svg"},
    "_fd_build-open": {iconPath: "./icons/folders/build-open.svg"},
    _fd_bench: {iconPath: "./icons/folders/bench.svg"},
    "_fd_bench-open": {iconPath: "./icons/folders/bench-open.svg"},
    _fd_i18n: {iconPath: "./icons/folders/i18n.svg"},
    "_fd_i18n-open": {iconPath: "./icons/folders/i18n-open.svg"},
    _fd_views: {iconPath: "./icons/folders/views.svg"},
    "_fd_views-open": {iconPath: "./icons/folders/views-open.svg"},
    _fd_theme: {iconPath: "./icons/folders/theme.svg"},
    "_fd_theme-open": {iconPath: "./icons/folders/theme-open.svg"},
    _fd_db: {iconPath: "./icons/folders/db.svg"},
    "_fd_db-open": {iconPath: "./icons/folders/db-open.svg"},
    _fd_images: {iconPath: "./icons/folders/images.svg"},
    "_fd_images-open": {iconPath: "./icons/folders/images-open.svg"},
    _fd_save: {iconPath: "./icons/folders/save.svg"},
    "_fd_save-open": {iconPath: "./icons/folders/save-open.svg"},
    _fd_next: {iconPath: "./icons/folders/next.svg"},
    "_fd_next-open": {iconPath: "./icons/folders/next-open.svg"},
    _fd_app: {iconPath: "./icons/folders/app.svg"},
    "_fd_app-open": {iconPath: "./icons/folders/app-open.svg"},
    _fd_cypress: {iconPath: "./icons/folders/cypress.svg"},
    "_fd_cypress-open": {iconPath: "./icons/folders/cypress-open.svg"},
    _f_jest: {iconPath: "./icons/jest.svg"},
    _f_actionscript: {iconPath: "./icons/actionscript.png"},
    _f_android: {iconPath: "./icons/android.svg"},
    _f_angular: {iconPath: "./icons/angular.svg"},
    _f_apache: {iconPath: "./icons/apache.svg"},
    _f_applescript: {iconPath: "./icons/applescript.svg"},
    _f_autoit: {iconPath: "./icons/autoit.svg"},
    _f_binary: {iconPath: "./icons/binary.png"},
    _f_blade: {iconPath: "./icons/blade.svg"},
    _f_bower: {iconPath: "./icons/bower.svg"},
    _f_brunch: {iconPath: "./icons/brunch.svg"},
    _f_c: {iconPath: "./icons/c.png"},
    "_f_c-h": {iconPath: "./icons/c-h.png"},
    _f_cake: {iconPath: "./icons/cake.png"},
    _f_codekit: {iconPath: "./icons/codekit.svg"},
    _f_coffeescript: {iconPath: "./icons/coffeescript.svg"},
    _f_coldfusion: {iconPath: "./icons/coldfusion.png"},
    _f_cfm: {iconPath: "./icons/cfm.png"},
    _f_cfc: {iconPath: "./icons/cfc.png"},
    _f_clojure: {iconPath: "./icons/clojure.svg"},
    _f_cakephp: {iconPath: "./icons/cakephp.svg"},
    _f_cmake: {iconPath: "./icons/cmake.svg"},
    _f_cpp: {iconPath: "./icons/cpp.svg"},
    "_f_cpp-h": {iconPath: "./icons/cpp-h.png"},
    _f_crystal: {iconPath: "./icons/crystal.svg"},
    _f_csharp: {iconPath: "./icons/csharp.svg"},
    _f_css: {iconPath: "./icons/css.svg"},
    _f_database: {iconPath: "./icons/database.svg"},
    _f_database2: {iconPath: "./icons/database2.svg"},
    _f_docker: {iconPath: "./icons/docker.svg"},
    _f_dotenv: {iconPath: "./icons/dotenv.svg"},
    _f_dust: {iconPath: "./icons/dust.png"},
    _f_ejs: {iconPath: "./icons/ejs.svg"},
    _f_elixir: {iconPath: "./icons/elixir.svg"},
    _f_elm: {iconPath: "./icons/elm.svg"},
    _f_erlang: {iconPath: "./icons/erlang.png"},
    _f_eslint: {iconPath: "./icons/eslint.svg"},
    _f_exe: {iconPath: "./icons/exe.png"},
    _f_font: {iconPath: "./icons/font.svg"},
    _f_fsharp: {iconPath: "./icons/fsharp.svg"},
    _f_gherkin: {iconPath: "./icons/gherkin.png"},
    _f_git: {iconPath: "./icons/git.svg"},
    _f_go: {iconPath: "./icons/go.svg"},
    _f_gnu: {iconPath: "./icons/gnu.svg"},
    _f_gradle: {iconPath: "./icons/gradle.svg"},
    _f_graphviz: {iconPath: "./icons/graphviz.png"},
    _f_grunt: {iconPath: "./icons/grunt.svg"},
    _f_gulp: {iconPath: "./icons/gulp.svg"},
    _f_haml: {iconPath: "./icons/haml.png"},
    _f_handlebars: {iconPath: "./icons/handlebars.svg"},
    _f_haskell: {iconPath: "./icons/haskell.svg"},
    _f_haxe: {iconPath: "./icons/haxe.svg"},
    _f_html: {iconPath: "./icons/html.svg"},
    _f_illustrator: {iconPath: "./icons/illustrator.svg"},
    _f_image: {iconPath: "./icons/image.png"},
    _f_icon: {iconPath: "./icons/icon.png"},
    _f_jade: {iconPath: "./icons/jade.svg"},
    _f_java: {iconPath: "./icons/java.svg"},
    "_f_java-alt": {iconPath: "./icons/java-alt.svg"},
    _f_javascript: {iconPath: "./icons/javascript.svg"},
    _f_jenkinsfile: {iconPath: "./icons/jenkins.svg"},
    _f_json: {iconPath: "./icons/json.svg"},
    _f_julia: {iconPath: "./icons/julia.svg"},
    _f_karma: {iconPath: "./icons/karma.svg"},
    _f_key: {iconPath: "./icons/key.png"},
    _f_less: {iconPath: "./icons/less.svg"},
    _f_liquid: {iconPath: "./icons/liquid.svg"},
    _f_markdown: {iconPath: "./icons/markdown.svg"},
    _f_matlab: {iconPath: "./icons/matlab.svg"},
    "_f_matlab-alt": {iconPath: "./icons/matlab-red.svg"},
    _f_mdx: {iconPath: "./icons/mdx.svg"},
    _f_mjml: {iconPath: "./icons/mjml.svg"},
    _f_mocha: {iconPath: "./icons/mocha.svg"},
    _f_mustache: {iconPath: "./icons/mustache.png"},
    _f_nginx: {iconPath: "./icons/nginx.svg"},
    _f_nim: {iconPath: "./icons/nim.svg"},
    _f_node: {iconPath: "./icons/node.svg"},
    _f_npm: {iconPath: "./icons/npm.svg"},
    _f_nsis: {iconPath: "./icons/nsis.svg"},
    _f_nuget: {iconPath: "./icons/nuget.svg"},
    _f_nunjucks: {iconPath: "./icons/nunjucks.svg"},
    _f_ocaml: {iconPath: "./icons/ocaml.svg"},
    _f_paket: {iconPath: "./icons/paket.png"},
    _f_pdf: {iconPath: "./icons/pdf.svg"},
    _f_perl: {iconPath: "./icons/perl.png"},
    _f_phalcon: {iconPath: "./icons/phalcon.svg"},
    _f_photoshop: {iconPath: "./icons/photoshop.svg"},
    _f_php: {iconPath: "./icons/php.svg"},
    _f_postcss: {iconPath: "./icons/postcss.svg"},
    _f_powershell: {iconPath: "./icons/powershell.png"},
    _f_pug: {iconPath: "./icons/pug.png"},
    _f_python: {iconPath: "./icons/python.svg"},
    _f_razor: {iconPath: "./icons/razor.png"},
    _f_react: {iconPath: "./icons/react.svg"},
    _f_react_alt: {iconPath: "./icons/react-alt.svg"},
    _f_rlang: {iconPath: "./icons/rlang.png"},
    _f_ruby: {iconPath: "./icons/ruby.svg"},
    _f_rust: {iconPath: "./icons/rust.svg"},
    _f_sass: {iconPath: "./icons/sass.svg"},
    _f_scala: {iconPath: "./icons/scala.svg"},
    _f_settings: {iconPath: "./icons/settings.svg"},
    "_f_settings-red": {iconPath: "./icons/settings-red.svg"},
    _f_shell: {iconPath: "./icons/shell.png"},
    _f_slim: {iconPath: "./icons/slim.svg"},
    _f_source: {iconPath: "./icons/source.svg"},
    _f_stylus: {iconPath: "./icons/stylus.svg"},
    _f_sublime: {iconPath: "./icons/sublime.svg"},
    _f_svg: {iconPath: "./icons/svg.svg"},
    _f_swift: {iconPath: "./icons/swift.svg"},
    _f_tcl: {iconPath: "./icons/tcl.png"},
    _f_tests: {iconPath: "./icons/test.svg"},
    _f_testsjs: {iconPath: "./icons/testjs.svg"},
    _f_tex: {iconPath: "./icons/tex.svg"},
    _f_textile: {iconPath: "./icons/textile.png"},
    _f_todo: {iconPath: "./icons/todo.svg"},
    _f_twig: {iconPath: "./icons/twig.png"},
    _f_typescript: {iconPath: "./icons/typescript.svg"},
    _f_url: {iconPath: "./icons/url.png"},
    _f_valgrind: {iconPath: "./icons/valgrind.svg"},
    _f_visualstudio: {iconPath: "./icons/visualstudio.svg"},
    _f_visualstudiocode: {iconPath: "./icons/visualstudiocode.svg"},
    _f_vue: {iconPath: "./icons/vue.svg"},
    _f_vitejs: {iconPath: "./icons/vitejs.svg"},
    _f_snowpackjs: {iconPath: "./icons/snowpackjs.svg"},
    _f_webpack: {iconPath: "./icons/webpack.svg"},
    _f_yaml: {iconPath: "./icons/yml.svg"},
    _f_yarn: {iconPath: "./icons/yarn.svg"},
    _f_zephir: {iconPath: "./icons/zephir.svg"},
    _f_zip: {iconPath: "./icons/zip.svg"},
    _f_audio: {iconPath: "./icons/audio.png"},
    _f_video: {iconPath: "./icons/video.png"},
    _f_word: {iconPath: "./icons/word.svg"},
    _f_excel: {iconPath: "./icons/excel.svg"},
    _f_powerpoint: {iconPath: "./icons/powerpoint.svg"},
    _f_favicon: {iconPath: "./icons/favicon.svg"},
    _f_xaml: {iconPath: "./icons/xaml.png"},
    _f_unity: {iconPath: "./icons/unity.svg"},
    _f_contributing: {iconPath: "./icons/contributing.png"},
    _f_smarty: {iconPath: "./icons/smarty.png"},
    _f_certificate: {iconPath: "./icons/certificate.png"},
    _f_babel: {iconPath: "./icons/babel.svg"},
    _f_gitlab: {iconPath: "./icons/gitlab.svg"},
    _f_arduino: {iconPath: "./icons/arduino.svg"},
    _f_opengl: {iconPath: "./icons/opengl.svg"},
    _f_dart: {iconPath: "./icons/dart.svg"},
    _f_puppet: {iconPath: "./icons/puppet.svg"},
    _f_rstudio: {iconPath: "./icons/rstudio.svg"},
    _f_solidity: {iconPath: "./icons/solidity.svg"},
    _f_lua: {iconPath: "./icons/lua.svg"},
    _f_server: {iconPath: "./icons/server.png"},
    _f_rollup: {iconPath: "./icons/rollup.svg"},
    _f_editorconfig: {iconPath: "./icons/editorconfig.png"},
    _f_json5: {iconPath: "./icons/json5.svg"},
    _f_graphql: {iconPath: "./icons/graphql.svg"},
    _f_graphqls: {iconPath: "./icons/graphqls.svg"},
    _f_prettier: {iconPath: "./icons/prettier.svg"},
    _f_cuda: {iconPath: "./icons/cuda.svg"},
    _f_foxpro: {iconPath: "./icons/foxpro.png"},
    _f_kotlin: {iconPath: "./icons/kotlin.svg"},
    _f_pascal: {iconPath: "./icons/pascal.png"},
    _f_pascalproject: {iconPath: "./icons/pascal-project.svg"},
    _f_harbour: {iconPath: "./icons/harbour.svg"},
    _f_terraform: {iconPath: "./icons/terraform.svg"},
    _f_visualbasic: {iconPath: "./icons/visualbasic.svg"},
    _f_rst: {iconPath: "./icons/rst.png"},
    _f_tslint: {iconPath: "./icons/tslint.svg"},
    _f_reason: {iconPath: "./icons/reason.svg"},
    _f_rescript: {iconPath: "./icons/rescript.svg"},
    _f_bucklescript: {iconPath: "./icons/buckle.png"},
    _f_jupyter: {iconPath: "./icons/jupyter.svg"},
    _f_axure: {iconPath: "./icons/axure.png"},
    _f_d: {iconPath: "./icons/d.png"},
    _f_livescript: {iconPath: "./icons/livescript.svg"},
    _f_stylelint: {iconPath: "./icons/stylelint.png"},
    _f_docz: {iconPath: "./icons/docz.png"},
    _f_prisma: {iconPath: "./icons/prisma.svg"},
    _f_toml: {iconPath: "./icons/toml.png"},
    _f_storybook: {iconPath: "./icons/storybook.svg"},
    _f_verilog: {iconPath: "./icons/verilog.png"},
    _f_verilog_sys: {iconPath: "./icons/verilog.png"},
    _f_moleculer: {iconPath: "./icons/moleculer.svg"},
    _f_svelte: {iconPath: "./icons/svelte.svg"},
    _f_mwb: {iconPath: "./icons/mysql-workbench.svg"},
    _f_sketch: {iconPath: "./icons/sketch.svg"},
    _f_figma: {iconPath: "./icons/figma.svg"},
    _f_sequelize: {iconPath: "./icons/sequelize.svg"},
    _f_dhall: {iconPath: "./icons/dhall.svg"},
    _f_nix: {iconPath: "./icons/nix.svg"},
    _f_purescript: {iconPath: "./icons/purescript.svg"},
    _f_scheme: {iconPath: "./icons/scheme.svg"},
    _f_racket: {iconPath: "./icons/racket.svg"},
    _f_jinja: {iconPath: "./icons/jinja.svg"},
    _f_abelljs: {iconPath: "./icons/abell.svg"},
    _f_webassembly: {iconPath: "./icons/wasm.svg"},
    _f_log: {iconPath: "./icons/log.svg"},
    _f_notepad: {iconPath: "./icons/notepad.svg"},
    _f_browserlist: {iconPath: "./icons/browserlist.svg"},
    _f_symfony: {iconPath: "./icons/symfony.svg"},
    _f_nextflow: {iconPath: "./icons/nextflow.png"},
    _f_singularity: {iconPath: "./icons/singularity.svg"},
    _f_fortran: {iconPath: "./icons/fortran.svg"},
    _f_oso: {iconPath: "./icons/oso.png"},
    _f_asciidoc: {iconPath: "./icons/asciidoc.svg"},
    _f_asp: {iconPath: "./icons/dotnet.svg"},
    _f_vim: {iconPath: "./icons/vim.svg"},
    _f_keystone: {iconPath: "./icons/keystone.svg"},
    _f_vitest: {iconPath: "./icons/vitest.svg"},
    _f_turborepo: {iconPath: "./icons/turborepo.svg"},
    _f_proto: {iconPath: "./icons/proto.svg"},
    _f_godot: {iconPath: "./icons/godot.svg"},
    _f_tailwind: {iconPath: "./icons/tailwind.svg"},
    _f_pnpm: {iconPath: "./icons/pnpm.svg"},
    _f_assembly: {iconPath: "./icons/assembly.svg"},
    _f_sentry: {iconPath: "./icons/sentry.svg"},
    _f_bicep: {iconPath: "./icons/bicep.png"},
    _f_vercel: {iconPath: "./icons/vercel.svg"},
    _f_nextjs: {iconPath: "./icons/nextjs.svg"},
    _f_firebase: {iconPath: "./icons/firebase.svg"},
    _f_avalonia: {iconPath: "./icons/avalonia.svg"},
    _f_marko: {iconPath: "./icons/marko.svg"},
    _f_model: {iconPath: "./icons/model.svg"},
    _f_serverless: {iconPath: "./icons/serverless.png"},
    _f_xi: {iconPath: "./icons/xi.svg"},
    _f_zig: {iconPath: "./icons/zig.svg"},
    _f_brainfuck: {iconPath: "./icons/brainfuck.svg"},
    _f_cython: {iconPath: "./icons/cython.svg"},
    _f_cypress: {iconPath: "./icons/cypress.svg"},
    _f_objectivec: {iconPath: "./icons/objectivec.svg"},
    _f_objectivecpp: {iconPath: "./icons/objectivecpp.svg"},
    _f_flowtyped: {iconPath: "./icons/flow.svg"},
    _f_vr: {iconPath: "./icons/vr.svg"},
    _f_prql: {iconPath: "./icons/database2.svg"},
    _f_prolog: {iconPath: "./icons/swi-prolog.svg"},
    _f_groovy: {iconPath: "./icons/groovy.svg"},
    _f_yak: {iconPath: "./icons/yak.svg"}
}

/** 默认文件图标 */
export const FileDefault = "_file"
/** 默认文件夹图标 */
export const FolderDefault = "_fd_default"
/** 默认文件夹打开图标 */
export const FolderDefaultExpanded = "_fd_default-open"

/** @name 文件后缀对应图标 */
export const FileSuffix: Record<string, string> = {
    ai: "_f_illustrator",
    as: "_f_actionscript",
    au3: "_f_autoit",
    htaccess: "_f_apache",
    htaccess_local: "_f_apache",
    htaccess_notlive: "_f_apache",
    htpasswd: "_f_apache",
    bin: "_f_binary",
    o: "_f_binary",
    lib: "_f_binary",
    dll: "_f_binary",
    obj: "_f_binary",
    a: "_f_binary",
    so: "_f_binary",
    pyc: "_f_binary",
    exe: "_f_exe",
    bowerrc: "_f_bower",
    c: "_f_c",
    h: "_f_c-h",
    cake: "_f_cake",
    kit: "_f_codekit",
    coffee: "_f_coffeescript",
    cfc: "_f_cfm",
    cfm: "_f_cfm",
    cfml: "_f_cfm",
    clj: "_f_clojure",
    cljs: "_f_clojure",
    cljc: "_f_clojure",
    edn: "_f_clojure",
    ctp: "_f_cakephp",
    lucee: "_f_coldfusion",
    cmake: "_f_cmake",
    "cmakelists.txt": "_f_cmake",
    cc: "_f_cpp",
    cpp: "_f_cpp",
    hpp: "_f_cpp-h",
    hh: "_f_cpp-h",
    cxx: "_f_cpp",
    cr: "_f_crystal",
    cs: "_f_csharp",
    cshtml: "_f_razor",
    csproj: "_f_visualstudio",
    css: "_f_css",
    dockerignore: "_f_docker",
    dockerfile: "_f_docker",
    "dockerfile.environment": "_f_docker",
    "environment.dockerfile": "_f_docker",
    "docker-compose.dev.yml": "_f_docker",
    "docker-compose-dev.yml": "_f_docker",
    "docker-compose.prod.yml": "_f_docker",
    "docker-compose-prod.yml": "_f_docker",
    "docker-compose.dist.yml": "_f_docker",
    "docker-compose-dist.yml": "_f_docker",
    "dockerfile.dev": "_f_docker",
    "dockerfile.prod": "_f_docker",
    "dockerfile.dist": "_f_docker",
    dust: "_f_dust",
    ejs: "_f_ejs",
    eslintignore: "_f_eslint",
    ex: "_f_elixir",
    exs: "_f_elixir",
    eex: "_f_elixir",
    leex: "_f_elixir",
    heex: "_f_elixir",
    elm: "_f_elm",
    erl: "_f_erlang",
    hrl: "_f_erlang",
    emakefile: "_f_erlang",
    emakerfile: "_f_erlang",
    woff: "_f_font",
    woff2: "_f_font",
    ttf: "_f_font",
    otf: "_f_font",
    eot: "_f_font",
    pfa: "_f_font",
    pfb: "_f_font",
    feature: "_f_gherkin",
    fs: "_f_fsharp",
    fsproj: "_f_visualstudio",
    fsx: "_f_fsharp",
    fsi: "_f_fsharp",
    gitattributes: "_f_git",
    gitmodules: "_f_git",
    go: "_f_go",
    gradle: "_f_gradle",
    haml: "_f_haml",
    has: "_f_haskell",
    hs: "_f_haskell",
    lhs: "_f_haskell",
    lit: "_f_haskell",
    gf: "_f_haskell",
    hbs: "_f_handlebars",
    "hbs.html": "_f_handlebars",
    hx: "_f_haxe",
    hxml: "_f_haxe",
    htm: "_f_html",
    html: "_f_html",
    jpeg: "_f_image",
    jpg: "_f_image",
    gif: "_f_image",
    png: "_f_image",
    bmp: "_f_image",
    ico: "_f_icon",
    webp: "_f_image",
    jade: "_f_jade",
    pug: "_f_pug",
    java: "_f_java",
    class: "_f_java-alt",
    jar: "_f_java",
    js: "_f_javascript",
    es6: "_f_javascript",
    json: "_f_json",
    jl: "_f_julia",
    key: "_f_key",
    pub: "_f_key",
    pem: "_f_key",
    asc: "_f_key",
    ppk: "_f_key",
    less: "_f_less",
    liquid: "_f_liquid",
    md: "_f_markdown",
    markdown: "_f_markdown",
    mdx: "_f_mdx",
    mjml: "_f_mjml",
    fig: "_f_figma",
    mat: "_f_matlab",
    mex: "_f_matlab",
    mexn: "_f_matlab",
    mexrs6: "_f_matlab",
    mn: "_f_matlab",
    mum: "_f_matlab",
    mx: "_f_matlab",
    mx3: "_f_matlab",
    rwd: "_f_matlab",
    slx: "_f_matlab",
    slddc: "_f_matlab",
    smv: "_f_matlab",
    tikz: "_f_matlab",
    xvc: "_f_matlab",
    mst: "_f_mustache",
    nconf: "_f_nginx",
    webmanifest: "_f_node",
    nuspec: "_f_nuget",
    nupkg: "_f_nuget",
    nim: "_f_nim",
    nunjucks: "_f_nunjucks",
    nunjs: "_f_nunjucks",
    nj: "_f_nunjucks",
    njhtml: "_f_nunjucks",
    njk: "_f_nunjucks",
    npmignore: "_f_npm",
    ml: "_f_ocaml",
    mll: "_f_ocaml",
    mli: "_f_ocaml",
    mly: "_f_ocaml",
    ocamlmakefile: "_f_ocaml",
    merlin: "_f_ocaml",
    pdf: "_f_pdf",
    postcss: "_f_postcss",
    postcssrc: "_f_postcss",
    pcss: "_f_postcss",
    perl: "_f_perl",
    pl: "_f_perl",
    pm: "_f_perl",
    php: "_f_php",
    php1: "_f_php",
    php2: "_f_php",
    php3: "_f_php",
    php4: "_f_php",
    php5: "_f_php",
    php6: "_f_php",
    phps: "_f_php",
    phpsa: "_f_php",
    phpt: "_f_php",
    phtml: "_f_php",
    phar: "_f_php",
    ps1: "_f_powershell",
    psc1: "_f_powershell",
    psm1: "_f_powershell",
    ps1xml: "_f_powershell",
    psd1: "_f_powershell",
    pssc: "_f_powershell",
    psd: "_f_photoshop",
    py: "_f_python",
    pyw: "_f_python",
    jsx: "_f_react",
    tsx: "_f_react_alt",
    r: "_f_rlang",
    R: "_f_rlang",
    RData: "_f_rlang",
    rda: "_f_rlang",
    rds: "_f_rlang",
    rprofile: "_f_rlang",
    Rprofile: "_f_rlang",
    rb: "_f_ruby",
    rbs: "_f_ruby",
    erb: "_f_ruby",
    gemfile: "_f_ruby",
    gemspec: "_f_ruby",
    rs: "_f_rust",
    scala: "_f_scala",
    sass: "_f_sass",
    "service.js": "_f_moleculer",
    "service.ts": "_f_moleculer",
    scss: "_f_sass",
    sss: "_f_postcss",
    sln: "_f_visualstudio",
    suo: "_f_visualstudio",
    supp: "_f_valgrind",
    slim: "_f_slim",
    slm: "_f_slim",
    env: "_f_dotenv",
    "env.example": "_f_dotenv",
    "env.development": "_f_dotenv",
    "env.production": "_f_dotenv",
    "env.production.example": "_f_dotenv",
    "env.development.local": "_f_dotenv",
    "env.production.local": "_f_dotenv",
    "env.local": "_f_dotenv",
    "env.local.example": "_f_dotenv",
    "env.test": "_f_dotenv",
    "env.accept": "_f_dotenv",
    "env.acceptance": "_f_dotenv",
    "env.staging": "_f_dotenv",
    "env.staging.example": "_f_dotenv",
    "env.dev": "_f_dotenv",
    ini: "_f_settings",
    conf: "_f_settings",
    properties: "_f_settings",
    load: "_f_settings",
    opt: "_f_settings",
    cnf: "_f_settings",
    makefile: "_f_settings-red",
    rake: "_f_ruby",
    rakefile: "_f_ruby",
    mk: "_f_settings-red",
    config: "_f_settings",
    bat: "_f_shell",
    sh: "_f_shell",
    cmd: "_f_shell",
    bash: "_f_shell",
    zsh: "_f_shell",
    fish: "_f_shell",
    "sublime-project": "_f_sublime",
    "sublime-workspace": "_f_sublime",
    sqlite: "_f_database2",
    sqlite2: "_f_database2",
    sqlite3: "_f_database2",
    sql: "_f_database",
    myd: "_f_database",
    myi: "_f_database",
    ibd: "_f_database",
    trn: "_f_database",
    mysql_hystory: "_f_database",
    db: "_f_database2",
    db2: "_f_database2",
    db3: "_f_database2",
    styl: "_f_stylus",
    stylus: "_f_stylus",
    svg: "_f_svg",
    swift: "_f_swift",
    "test.js": "_f_tests",
    "test.jsx": "_f_tests",
    "test.mjs": "_f_tests",
    "test.ts": "_f_tests",
    "tests.ts": "_f_tests",
    "test.tsx": "_f_tests",
    "tests.tsx": "_f_tests",
    "spec.js": "_f_tests",
    "spec.ts": "_f_tests",
    "spec.tsx": "_f_tests",
    "unit.js": "_f_tests",
    "unit.ts": "_f_tests",
    "unit.tsx": "_f_tests",
    tcl: "_f_tcl",
    texi: "_f_tex",
    tex: "_f_tex",
    bib: "_f_tex",
    textile: "_f_textile",
    todo: "_f_todo",
    twig: "_f_twig",
    ts: "_f_typescript",
    vue: "_f_vue",
    xml: "_f_source",
    axml: "_f_source",
    xaml: "_f_source",
    pex: "_f_source",
    yml: "_f_yaml",
    yaml: "_f_yaml",
    yarnclean: "_f_yarn",
    zip: "_f_zip",
    rar: "_f_zip",
    "7z": "_f_zip",
    tar: "_f_zip",
    gz: "_f_zip",
    bzip2: "_f_zip",
    xz: "_f_zip",
    bz2: "_f_zip",
    "blade.php": "_f_blade",
    nsi: "_f_nsis",
    nsh: "_f_nsis",
    volt: "_f_phalcon",
    zep: "_f_zephir",
    mp3: "_f_audio",
    wav: "_f_audio",
    flac: "_f_audio",
    m4a: "_f_audio",
    aiff: "_f_audio",
    wma: "_f_audio",
    mov: "_f_video",
    webm: "_f_video",
    mp4: "_f_video",
    mpg: "_f_video",
    mpeg: "_f_video",
    mkv: "_f_video",
    flv: "_f_video",
    vob: "_f_video",
    ogv: "_f_video",
    ogg: "_f_video",
    avi: "_f_video",
    m4v: "_f_video",
    qt: "_f_video",
    mp2: "_f_video",
    ppt: "_f_powerpoint",
    pptx: "_f_powerpoint",
    pptm: "_f_powerpoint",
    pot: "_f_powerpoint",
    potm: "_f_powerpoint",
    potx: "_f_powerpoint",
    pps: "_f_powerpoint",
    ppsm: "_f_powerpoint",
    ppsx: "_f_powerpoint",
    ppa: "_f_powerpoint",
    ppam: "_f_powerpoint",
    doc: "_f_word",
    docm: "_f_word",
    docx: "_f_word",
    dot: "_f_word",
    dotm: "_f_word",
    dotx: "_f_word",
    rtf: "_f_word",
    xla: "_f_excel",
    xlam: "_f_excel",
    xls: "_f_excel",
    xlsb: "_f_excel",
    xlsm: "_f_excel",
    xlsx: "_f_excel",
    xlt: "_f_excel",
    xltm: "_f_excel",
    xltx: "_f_excel",
    csv: "_f_excel",
    tsv: "_f_excel",
    cer: "_f_certificate",
    babelrc: "_f_babel",
    "gitlab-ci.yaml": "_f_gitlab",
    "gitlab-ci.yml": "_f_gitlab",
    ino: "_f_arduino",
    glsl: "_f_opengl",
    geom: "_f_opengl",
    comp: "_f_opengl",
    tesc: "_f_opengl",
    tese: "_f_opengl",
    vs: "_f_opengl",
    frag: "_f_opengl",
    vert: "_f_opengl",
    rchit: "_f_opengl",
    task: "_f_opengl",
    dart: "_f_dart",
    pp: "_f_puppet",
    rproj: "_f_rstudio",
    sol: "_f_solidity",
    lua: "_f_lua",
    http: "_f_server",
    json5: "_f_json5",
    gql: "_f_graphql",
    graphql: "_f_graphql",
    gqls: "_f_graphqls",
    graphqls: "_f_graphqls",
    m: "_f_matlab-alt",
    cu: "_f_cuda",
    kt: "_f_kotlin",
    kts: "_f_kotlin",
    fxp: "_f_foxpro",
    pas: "_f_pascal",
    dpr: "_f_pascalproject",
    lpr: "_f_pascalproject",
    hbp: "_f_harbour",
    hbc: "_f_harbour",
    prg: "_f_exe",
    tf: "_f_terraform",
    tfvars: "_f_terraform",
    vb: "_f_visualbasic",
    cls: "_f_visualbasic",
    frm: "_f_visualbasic",
    bas: "_f_visualbasic",
    doccls: "_f_visualbasic",
    rst: "_f_rst",
    re: "_f_reason",
    rei: "_f_reason",
    res: "_f_rescript",
    resi: "_f_rescript",
    ipynb: "_f_jupyter",
    rp: "_f_axure",
    d: "_f_d",
    di: "_f_d",
    msbuild: "_f_visualstudiocode",
    props: "_f_settings",
    targets: "_f_settings",
    proj: "_f_visualstudio",
    jsproj: "_f_visualstudio",
    sqlproj: "_f_visualstudio",
    vbproj: "_f_visualstudio",
    vcxproj: "_f_visualstudio",
    wixproj: "_f_visualstudio",
    dbproj: "_f_visualstudio",
    lsproj: "_f_visualstudio",
    modelproj: "_f_visualstudio",
    vcproj: "_f_visualstudio",
    wwaproj: "_f_visualstudio",
    ls: "_f_livescript",
    stylelintrc: "_f_stylelint",
    stylelintignore: "_f_stylelint",
    htmlhintrc: "_f_settings",
    prisma: "_f_prisma",
    toml: "_f_toml",
    "story.js": "_f_storybook",
    "story.jsx": "_f_storybook",
    "story.ts": "_f_storybook",
    "story.tsx": "_f_storybook",
    "stories.js": "_f_storybook",
    "stories.jsx": "_f_storybook",
    "stories.ts": "_f_storybook",
    "stories.tsx": "_f_storybook",
    storybook: "_f_storybook",
    v: "_f_verilog",
    vh: "_f_verilog",
    vo: "_f_verilog",
    sv: "_f_verilog_sys",
    vhd: "_f_verilog",
    vhdl: "_f_verilog",
    svelte: "_f_svelte",
    "svelte.js": "_f_svelte",
    "svelte.ts": "_f_svelte",
    razor: "_f_razor",
    mwb: "_f_mwb",
    "mwb.beforefix": "_f_mwb",
    "mwb.bak": "_f_mwb",
    sketch: "_f_sketch",
    dhall: "_f_dhall",
    nix: "_f_nix",
    purs: "_f_purescript",
    purescript: "_f_purescript",
    rkt: "_f_racket",
    scm: "_f_scheme",
    sch: "_f_scheme",
    ss: "_f_scheme",
    rdl: "_f_database",
    j2: "_f_jinja",
    jinja: "_f_jinja",
    jinja2: "_f_jinja",
    vscodeignore: "_f_visualstudiocode",
    editorconfig: "_f_editorconfig",
    sequelizerc: "_f_sequelize",
    npmrc: "_f_npm",
    eslintrc: "_f_eslint",
    "eslintrc.js": "_f_eslint",
    "eslintrc.yml": "_f_eslint",
    "eslintrc.yaml": "_f_eslint",
    "eslintrc.json": "_f_eslint",
    browserlistrc: "_f_browserlist",
    browserslistrc: "_f_browserlist",
    gitkeep: "_f_git",
    abell: "_f_abelljs",
    wasm: "_f_webassembly",
    log: "_f_log",
    txt: "_f_notepad",
    nf: "_f_nextflow",
    def: "_f_singularity",
    f: "_f_fortran",
    for: "_f_fortran",
    f90: "_f_fortran",
    f95: "_f_fortran",
    ftn: "_f_fortran",
    fpp: "_f_fortran",
    polar: "_f_oso",
    adoc: "_f_asciidoc",
    asciidoc: "_f_asciidoc",
    asp: "_f_asp",
    asa: "_f_asp",
    aspx: "_f_asp",
    asax: "_f_asp",
    ascx: "_f_asp",
    vim: "_f_vim",
    proto: "_f_proto",
    gd: "_f_godot",
    tscn: "_f_godot",
    asm: "_f_assembly",
    s: "_f_assembly",
    sentryclirc: "_f_sentry",
    marko: "_f_marko",
    axaml: "_f_avalonia",
    "axaml.cs": "_f_avalonia",
    "model.ts": "_f_model",
    "model.js": "_f_model",
    xi: "_f_xi",
    zig: "_f_zig",
    bf: "_f_brainfuck",
    b: "_f_brainfuck",
    pyx: "_f_cython",
    pxd: "_f_cython",
    "cy.js": "_f_cypress",
    "cy.ts": "_f_cypress",
    "cy.jsx": "_f_cypress",
    mm: "_f_objectivecpp",
    "vr.js": "_f_vr",
    "vr.ts": "_f_vr",
    "vr.jsx": "_f_vr",
    "vr.cjs": "_f_vr",
    sqlbook: "_f_database",
    pro: "_f_prolog",
    "mocha.js": "_f_mocha",
    "mocha.ts": "_f_mocha",
    "mocha.cjs": "_f_mocha",
    groovy: "_f_groovy",
    jenkinsfile: "_f_jenkinsfile",
    yak: "_f_yak"
}

// 以下对象的设置暂未实现
const FolderNames: Record<string, string> = {
    ".build": "_fd_build",
    ".git": "_fd_git",
    ".github": "_fd_git",
    ".gitlab": "_fd_git",
    ".next": "_fd_next",
    ".out": "_fd_build",
    ".vscode": "_fd_vscode",
    ".vscode-test": "_fd_vscode",
    __mocks__: "_fd_tests",
    __snapshots: "_fd_jest",
    __tests__: "_fd_jest",
    app: "_fd_app",
    bak: "_fd_save",
    backup: "_fd_save",
    backups: "_fd_save",
    bench: "_fd_bench",
    benches: "_fd_bench",
    bower_components: "_fd_bower",
    build: "_fd_build",
    config: "_fd_bench",
    cypress: "_fd_cypress",
    db: "_fd_db",
    database: "_fd_db",
    databases: "_fd_db",
    i18n: "_fd_i18n",
    images: "_fd_images",
    img: "_fd_images",
    lang: "_fd_i18n",
    language: "_fd_i18n",
    languages: "_fd_i18n",
    mocks: "_fd_tests",
    node_modules: "_fd_node",
    out: "_fd_build",
    save: "_fd_save",
    saves: "_fd_save",
    sql: "_fd_db",
    sql_schema: "_fd_db",
    sqlite: "_fd_db",
    stubs: "_fd_tests",
    test: "_fd_tests",
    tests: "_fd_tests",
    theme: "_fd_theme",
    themes: "_fd_theme",
    view: "_fd_views",
    views: "_fd_views"
}
const FolderNamesExpanded: Record<string, string> = {
    ".build": "_fd_build-open",
    ".git": "_fd_git-open",
    ".github": "_fd_git-open",
    ".gitlab": "_fd_git-open",
    ".next": "_fd_next-open",
    ".out": "_fd_build-open",
    ".vscode": "_fd_vscode-open",
    ".vscode-test": "_fd_vscode-open",
    __mocks__: "_fd_tests-open",
    __snapshots: "_fd_jest-open",
    __tests__: "_fd_jest-open",
    app: "_fd_app-open",
    bak: "_fd_save-open",
    backup: "_fd_save-open",
    backups: "_fd_save-open",
    bench: "_fd_bench-open",
    benches: "_fd_bench-open",
    build: "_fd_build-open",
    bower_components: "_fd_bower-open",
    config: "_fd_build-open",
    cypress: "_fd_cypress-open",
    db: "_fd_db-open",
    database: "_fd_db-open",
    databases: "_fd_db-open",
    i18n: "_fd_i18n-open",
    images: "_fd_images-open",
    img: "_fd_images-open",
    lang: "_fd_i18n-open",
    language: "_fd_i18n-open",
    languages: "_fd_i18n-open",
    mocks: "_fd_tests-open",
    node_modules: "_fd_node-open",
    out: "_fd_build-open",
    save: "_fd_save-open",
    saves: "_fd_save-open",
    sql: "_fd_db-open",
    sql_schema: "_fd_db-open",
    sqlite: "_fd_db-open",
    stubs: "_fd_tests-open",
    test: "_fd_tests-open",
    tests: "_fd_tests-open",
    theme: "_fd_theme-open",
    themes: "_fd_theme-open",
    view: "_fd_views-open",
    views: "_fd_views-open"
}

const FileNames: Record<string, string> = {
    "androidmanifest.xml": "_f_android",
    "bower.json": "_f_bower",
    "brunch-config.js": "_f_brunch",
    "brunch-config.cjs": "_f_brunch",
    "brunch-config.ts": "_f_brunch",
    "brunch-config.coffee": "_f_brunch",
    "cmakelists.txt": "_f_cmake",
    makefile: "_f_settings-red",
    rakefile: "_f_ruby",
    "docker-compose.yml": "_f_docker",
    "docker.yml": "_f_docker",
    "docker.yaml": "_f_docker",
    dockerfile: "_f_docker",
    "dockerfile.environment": "_f_docker",
    "environment.dockerfile": "_f_docker",
    "nginx.dockerfile": "_f_docker",
    "gruntfile.js": "_f_grunt",
    "gruntfile.cjs": "_f_grunt",
    "gruntfile.mjs": "_f_grunt",
    "gruntfile.ts": "_f_grunt",
    "gruntfile.coffee": "_f_grunt",
    "gulpfile.js": "_f_gulp",
    "gulpfile.cjs": "_f_gulp",
    "gulpfile.mjs": "_f_gulp",
    "gulpfile.ts": "_f_gulp",
    "gulpfile.coffee": "_f_gulp",
    "gulpfile.esm.js": "_f_gulp",
    "gulpfile.esm.cjs": "_f_gulp",
    "gulpfile.esm.ts": "_f_gulp",
    "gulpfile.esm.coffee": "_f_gulp",
    "gulpfile.babel.js": "_f_gulp",
    "gulpfile.babel.cjs": "_f_gulp",
    "gulpfile.babel.ts": "_f_gulp",
    "gulpfile.babel.coffee": "_f_gulp",
    jenkinsfile: "_f_jenkinsfile",
    "karma.conf.js": "_f_karma",
    "karma.conf.cjs": "_f_karma",
    "karma.conf.ts": "_f_karma",
    "karma.conf.coffee": "_f_karma",
    license: "_f_key",
    license_mit: "_f_key",
    license_apache: "_f_key",
    licence: "_f_key",
    "license.md": "_f_key",
    "licence.md": "_f_key",
    "mocha.opts": "_f_mocha",
    "moleculer.config.js": "_f_moleculer",
    "moleculer.config.json": "_f_moleculer",
    "moleculer.config.ts": "_f_moleculer",
    "package.json": "_f_npm",
    "package-lock.json": "_f_npm",
    "npm-debug.log": "_f_npm",
    "paket.references": "_f_paket",
    "paket.dependencies": "_f_paket",
    "paket.lock": "_f_paket",
    "paket.local": "_f_paket",
    gemfile: "_f_ruby",
    "gemfile.lock": "_f_ruby",
    "vscodeignore.json": "_f_visualstudiocode",
    "extensions.json": "_f_visualstudiocode",
    "launch.json": "_f_visualstudiocode",
    "settings.json": "_f_visualstudiocode",
    "tasks.json": "_f_visualstudiocode",
    "jsconfig.json": "_f_json",
    "tsconfig.json": "_f_json",
    "vite.config.js": "_f_vitejs",
    "vite.config.ts": "_f_vitejs",
    "vite.config.cjs": "_f_vitejs",
    "snowpack.config.js": "_f_snowpackjs",
    "snowpack.config.ts": "_f_snowpackjs",
    "snowpack.config.cjs": "_f_snowpackjs",
    "webpack.js": "_f_webpack",
    "webpack.cjs": "_f_webpack",
    "webpack.ts": "_f_webpack",
    "webpack.config.js": "_f_webpack",
    "webpack.config.cjs": "_f_webpack",
    "webpack.config.mjs": "_f_webpack",
    "webpack.config.ts": "_f_webpack",
    "webpack.dev.js": "_f_webpack",
    "webpack.dev.cjs": "_f_webpack",
    "webpack.dev.ts": "_f_webpack",
    "webpack.prod.js": "_f_webpack",
    "webpack.prod.cjs": "_f_webpack",
    "webpack.prod.ts": "_f_webpack",
    "webpack.common.js": "_f_webpack",
    "webpack.common.cjs": "_f_webpack",
    "webpack.common.ts": "_f_webpack",
    "webpack.conf.js": "_f_webpack",
    "webpack.conf.cjs": "_f_webpack",
    "webpack.conf.ts": "_f_webpack",
    "webpack.base.conf.js": "_f_webpack",
    "webpack.base.conf.cjs": "_f_webpack",
    "webpack.base.conf.ts": "_f_webpack",
    "webpack.dev.conf.js": "_f_webpack",
    "webpack.dev.conf.cjs": "_f_webpack",
    "webpack.dev.conf.ts": "_f_webpack",
    "webpack.prod.conf.js": "_f_webpack",
    "webpack.prod.conf.cjs": "_f_webpack",
    "webpack.prod.conf.ts": "_f_webpack",
    "webpack.base.js": "_f_webpack",
    "webpack.base.cjs": "_f_webpack",
    "webpack.base.ts": "_f_webpack",
    "webpack.config.common.js": "_f_webpack",
    "webpack.config.common.cjs": "_f_webpack",
    "webpack.config.common.ts": "_f_webpack",
    "webpack.config.common.babel.js": "_f_webpack",
    "webpack.config.common.babel.cjs": "_f_webpack",
    "webpack.config.common.babel.ts": "_f_webpack",
    "webpack.config.dev.js": "_f_webpack",
    "webpack.config.dev.cjs": "_f_webpack",
    "webpack.config.dev.ts": "_f_webpack",
    "webpack.config.dev.babel.js": "_f_webpack",
    "webpack.config.dev.babel.cjs": "_f_webpack",
    "webpack.config.dev.babel.ts": "_f_webpack",
    "webpack.config.production.babel.js": "_f_webpack",
    "webpack.config.production.babel.cjs": "_f_webpack",
    "webpack.config.production.babel.ts": "_f_webpack",
    "webpack.config.prod.babel.js": "_f_webpack",
    "webpack.config.prod.babel.cjs": "_f_webpack",
    "webpack.config.prod.babel.ts": "_f_webpack",
    "webpack.config.prod.js": "_f_webpack",
    "webpack.config.prod.cjs": "_f_webpack",
    "webpack.config.prod.ts": "_f_webpack",
    "webpack.config.production.js": "_f_webpack",
    "webpack.config.production.cjs": "_f_webpack",
    "webpack.config.production.ts": "_f_webpack",
    "webpack.config.staging.js": "_f_webpack",
    "webpack.config.staging.cjs": "_f_webpack",
    "webpack.config.staging.ts": "_f_webpack",
    "webpack.config.base.js": "_f_webpack",
    "webpack.config.base.cjs": "_f_webpack",
    "webpack.config.base.ts": "_f_webpack",
    "webpack.config.babel.js": "_f_webpack",
    "webpack.config.babel.cjs": "_f_webpack",
    "webpack.config.babel.ts": "_f_webpack",
    "webpack.config.base.babel.js": "_f_webpack",
    "webpack.config.base.babel.ts": "_f_webpack",
    "webpack.config.base.babel.cjs": "_f_webpack",
    "webpack.config.staging.babel.js": "_f_webpack",
    "webpack.config.staging.babel.ts": "_f_webpack",
    "webpack.config.staging.babel.cjs": "_f_webpack",
    "webpack.config.parts.js": "_f_webpack",
    "webpack.config.parts.ts": "_f_webpack",
    "webpack.config.parts.cjs": "_f_webpack",
    "webpack.config.coffee": "_f_webpack",
    "webpack.config.test.js": "_f_webpack",
    "webpack.config.test.ts": "_f_webpack",
    "webpack.config.test.cjs": "_f_webpack",
    "webpack.test.js": "_f_webpack",
    "webpack.test.ts": "_f_webpack",
    "webpack.test.cjs": "_f_webpack",
    "webpackfile.js": "_f_webpack",
    "webpackfile.ts": "_f_webpack",
    "webpackfile.cjs": "_f_webpack",
    "yarn.lock": "_f_yarn",
    "yarn-error.log": "_f_yarn",
    ".vscodeignore": "_f_visualstudiocode",
    ".editorconfig": "_f_editorconfig",
    ".sequelizerc": "_f_sequelize",
    ".babelrc": "_f_babel",
    ".babelrc.json": "_f_babel",
    "babel.config.json": "_f_babel",
    ".npmrc": "_f_npm",
    ".eslintrc": "_f_eslint",
    ".eslintrc.js": "_f_eslint",
    ".eslintrc.yml": "_f_eslint",
    ".eslintrc.yaml": "_f_eslint",
    ".eslintrc.json": "_f_eslint",
    ".eslintrc.ts": "_f_eslint",
    ".eslintrc.cjs": "_f_eslint",
    ".eslintrc.mjs": "_f_eslint",
    "eslint.config.js": "_f_eslint",
    "eslint.config.cjs": "_f_eslint",
    "eslint.config.mjs": "_f_eslint",
    ".stylelintrc": "_f_stylelint",
    ".stylelintrc.js": "_f_stylelint",
    ".stylelintrc.ts": "_f_stylelint",
    ".stylelintrc.cjs": "_f_stylelint",
    ".stylelintrc.mjs": "_f_stylelint",
    ".stylelintrc.yml": "_f_stylelint",
    ".stylelintrc.yaml": "_f_stylelint",
    ".stylelintrc.json": "_f_stylelint",
    ".gitlab-ci.yaml": "_f_gitlab",
    ".gitlab-ci.yml": "_f_gitlab",
    ".browserlistrc": "_f_browserlist",
    ".browserslistrc": "_f_browserlist",
    ".gitkeep": "_f_git",
    ".gitignore": "_f_git",
    "rollup.config.js": "_f_rollup",
    "rollup.config.ts": "_f_rollup",
    "rollup.config.cjs": "_f_rollup",
    "rollup.config.mjs": "_f_rollup",
    "rollup.config.coffee": "_f_rollup",
    "postcss.config.js": "_f_postcss",
    "postcss.config.ts": "_f_postcss",
    "postcss.config.cjs": "_f_postcss",
    "postcss.config.mjs": "_f_postcss",
    "postcss.config.json": "_f_postcss",
    ".prettierrc": "_f_prettier",
    ".prettierignore": "_f_prettier",
    ".prettierrc.js": "_f_prettier",
    ".prettierrc.ts": "_f_prettier",
    ".prettierrc.cjs": "_f_prettier",
    ".prettierrc.json": "_f_prettier",
    ".prettierrc.yml": "_f_prettier",
    ".prettierrc.yaml": "_f_prettier",
    ".prettierrc.toml": "_f_prettier",
    "prettier.config.js": "_f_prettier",
    "prettier.config.cjs": "_f_prettier",
    "prettier.config.ts": "_f_prettier",
    "prettier.config.coffee": "_f_prettier",
    "tslint.js": "_f_tslint",
    "tslint.ts": "_f_tslint",
    "tslint.cjs": "_f_tslint",
    "tslint.json": "_f_tslint",
    "bsconfig.json": "_f_bucklescript",
    ".bsb.lock": "_f_bucklescript",
    "dub.json": "_f_d",
    "jest.config.js": "_f_jest",
    "jest.config.ts": "_f_jest",
    "jest.config.cjs": "_f_jest",
    ".jest.config.js": "_f_jest",
    ".jest.config.ts": "_f_jest",
    ".jest.config.cjs": "_f_jest",
    "doczrc.js": "_f_docz",
    "@.toml": "_f_toml",
    envvars: "_f_dotenv",
    error_log: "_f_log",
    "blink.ino": "_f_arduino",
    "symfony.lock": "_f_symfony",
    Singularity: "_f_singularity",
    ".gvimrc": "_f_vim",
    ".vimrc": "_f_vim",
    Steepfile: "_f_ruby",
    "svelte.config": "_f_svelte",
    "keystone.ts": "_f_keystone",
    "vitest.config.js": "_f_vitest",
    "vitest.config.ts": "_f_vitest",
    "vitest.config.cjs": "_f_vitest",
    "turbo.json": "_f_turborepo",
    "tailwind.js": "_f_tailwind",
    "tailwind.ts": "_f_tailwind",
    "tailwind.cjs": "_f_tailwind",
    "tailwind.config.js": "_f_tailwind",
    "tailwind.config.ts": "_f_tailwind",
    "tailwind.config.cjs": "_f_tailwind",
    "pnpm-workspace.yaml": "_f_pnpm",
    "pnpm-workspace.js": "_f_pnpm",
    "pnpm-lock.yaml": "_f_pnpm",
    "pnpm-lock.js": "_f_pnpm",
    "pnpmfile.js": "_f_pnpm",
    "pnpmfile.ts": "_f_pnpm",
    "pnpmfile.cjs": "_f_pnpm",
    "sentry.client.js": "_f_sentry",
    "sentry.client.ts": "_f_sentry",
    "sentry.client.cjs": "_f_sentry",
    "sentry.server.js": "_f_sentry",
    "sentry.server.ts": "_f_sentry",
    "sentry.server.cjs": "_f_sentry",
    "sentry.properties": "_f_sentry",
    ".bicep": "_f_bicep",
    "vercel.json": "_f_vercel",
    "next.config.js": "_f_nextjs",
    "next.config.ts": "_f_nextjs",
    "next.config.cjs": "_f_nextjs",
    "next.config.mjs": "_f_nextjs",
    ".firebaserc": "_f_firebase",
    "firebase.json": "_f_firebase",
    "firebase.js": "_f_firebase",
    "firebase.ts": "_f_firebase",
    "firebase.cjs": "_f_firebase",
    "serverless.yml": "_f_serverless",
    "serverless.yaml": "_f_serverless",
    "cypress.json": "_f_cypress",
    "cypress.config.js": "_f_cypress",
    "cypress.config.ts": "_f_cypress",
    "cypress.config.jsx": "_f_cypress",
    "cypress.env.json": "_f_cypress",
    "go.mod": "_f_go",
    "flow-typed.config.json": "_f_flowtyped",
    "poetry.lock": "_f_toml"
}

const LanguageIds: Record<string, string> = {
    apache: "_f_apache",
    apacheconf: "_f_apache",
    nginx: "_f_nginx",
    git: "_f_git",
    "git-commit": "_f_git",
    "git-rebase": "_f_git",
    diff: "_f_git",
    ignore: "_f_git",
    bat: "_f_shell",
    c: "_f_c",
    cpp: "_f_cpp",
    coffeescript: "_f_coffeescript",
    nim: "_f_nim",
    csharp: "_f_csharp",
    dotenv: "_f_dotenv",
    fsharp: "_f_fsharp",
    xml: "_f_source",
    yaml: "_f_yaml",
    matlab: "_f_matlab",
    java: "_f_java",
    razor: "_f_razor",
    python: "_f_python",
    javascript: "_f_javascript",
    typescript: "_f_typescript",
    react: "_f_react",
    javascriptreact: "_f_javascript",
    typescriptreact: "_f_typescript",
    scala: "_f_scala",
    handlebars: "_f_handlebars",
    perl: "_f_perl",
    perl6: "_f_perl",
    haxe: "_f_haxe",
    hxml: "_f_haxe",
    puppet: "_f_puppet",
    elixir: "_f_elixir",
    erlang: "_f_erlang",
    twig: "_f_twig",
    elm: "_f_elm",
    nunjucks: "_f_nunjucks",
    pug: "_f_pug",
    stylus: "_f_stylus",
    svelte: "_f_svelte",
    sass: "_f_sass",
    scss: "_f_sass",
    less: "_f_less",
    css: "_f_css",
    "ng-template": "_f_angular",
    autoit: "_f_autoit",
    haml: "_f_haml",
    smarty: "_f_smarty",
    docker: "_f_docker",
    dockerfile: "_f_docker",
    dockercompose: "_f_docker",
    markdown: "_f_markdown",
    php: "_f_php",
    html: "_f_html",
    json: "_f_json",
    jsonl: "_f_json",
    dart: "_f_dart",
    cuda: "_f_cuda",
    pascal: "_f_pascal",
    foxpro: "_f_foxpro",
    harbour: "_f_harbour",
    visualbasic: "_f_visualbasic",
    webassembly: "_f_webassembly",
    env: "_f_dotenv",
    keystone: "_f_keystone",
    vitest: "_f_vitest",
    turbo: "_f_turborepo",
    assembly: "_f_assembly",
    marko: "_f_marko",
    xi: "_f_xi",
    clojure: "_f_clojure",
    editorconfig: "_f_editorconfig",
    go: "_f_go",
    ini: "_f_settings",
    julia: "_f_julia",
    juliamarkdown: "_f_julia",
    log: "_f_log",
    lua: "_f_lua",
    makefile: "_f_settings-red",
    plaintext: "_f_notepad",
    powershell: "_f_powershell",
    jade: "_f_pug",
    r: "_f_rlang",
    ruby: "_f_ruby",
    rust: "_f_rust",
    shellscript: "_f_shell",
    sql: "_f_database",
    swift: "_f_swift",
    tex: "_f_tex",
    vb: "_f_visualbasic",
    vue: "_f_vue",
    "vue-directives": "_f_vue",
    "vue-sfc-style-variable-injection": "_f_vue",
    "vue-interpoloations": "_f_vue",
    "vue-injection-markdown": "_f_vue",
    zig: "_f_zig",
    brainfuck: "_f_brainfuck",
    cython: "_f_cython",
    cypress: "_f_cypress",
    "objective-c": "_f_objectivec",
    "objective-cpp": "_f_objectivecpp",
    sqlbook: "_f_database",
    prql: "_f_prql",
    prolog: "_f_prolog",
    groovy: "_f_groovy"
}
