const serviceName = {
    AnalyzerApi: "AnalyzerApi",
    AssetsApi: "AssetsApi",
    AttachApi: "AttachApi",
    BruteApi: "BruteApi",
    ChaosMakerApi: "ChaosMakerApi",
    CodecApi: "CodecApi",
    CompletionApi: "CompletionApi",
    CrawlerApi: "CrawlerApi",
    CVEApi: "CVEApi",
    DocumentApi: "DocumentApi",
    YakScriptApi: "YakScriptApi",
    ExecYakScriptApi: "ExecYakScriptApi",
    ExportApi: "ExportApi",
    FacadesApi: "FacadesApi",
    TunnelApi: "TunnelApi",
    YsoSerialGoApi: "YsoSerialGoApi",
    FuzzerApi: "FuzzerApi",
    HTTPFlowApi: "HTTPFlowApi",
    GenerateCodeApi: "GenerateCodeApi",
    LicenseApi: "LicenseApi",
    MenuApi: "MenuApi",
    MiscApi: "MiscApi",
    MITMApi: "MITMApi",
    MITMReplacerApi: "MITMReplacerApi",
    MITMExtractedDataApi: "MITMExtractedDataApi",
    MITMFilterApi: "MITMFilterApi",
    OnlineApi: "OnlineApi",
    PayloadsApi: "PayloadsApi",
    PortScanApi: "PortScanApi",
    ProjectApi: "ProjectApi",
    ProxyApi: "ProxyApi",
    ReportApi: "ReportApi",
    RisksApi: "RisksApi",
    ScreenRecorderApi: "ScreenRecorderApi",
    StoreApi: "StoreApi",
    SystemProxyApi: "SystemProxyApi",
    UpdateApi: "UpdateApi",
    WebSocketApi: "WebSocketApi",
    YakApi: "YakApi",
    YakShellApi: "YakShellApi",
}


module.exports = {
    serviceName,
}