name: Gen-Multi-IRify-Platform-Render

on:
    workflow_dispatch:

jobs:
    build_yakit:
        if: ${{ startsWith(github.ref_name, 'v') && endsWith(github.ref_name, '-irify-render') }}
        runs-on: ubuntu-latest
        env:
            CI: ""
            NODE_OPTIONS: --max_old_space_size=4096
            RENDER_PATH: ./app/renderer
            RETURN_PATH: ../../

        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-node@v4
              with:
                  node-version: 18.18.2

            - name: Generate tag version
              run: |
                  echo $GITHUB_REF_NAME
                  tag=${GITHUB_REF_NAME#v}
                  tag=${tag%-irify-render}
                  echo ${tag}
                  echo "TAG_VERSION=$tag" >> $GITHUB_ENV

            - name: "Install Render Dependencies"
              run: yarn install-render
              working-directory: ./

            - name: "Build IRify Render"
              working-directory: ./
              run: yarn build-render-irify
            - name: "zip IRify Render"
              run: cd ${{ env.RENDER_PATH }} && zip -r irify.zip ./pages && rm -rf ./pages && cd ${{ env.RETURN_PATH }}

            - name: "Build IRifyEE Render"
              working-directory: ./
              run: yarn build-render-irify-enterprise
            - name: "zip IRifyEE Render"
              run: cd ${{ env.RENDER_PATH }} && zip -r irifyee.zip ./pages && rm -rf ./pages && cd ${{ env.RETURN_PATH }}

            - name: View Published Content
              run: ls ${{ env.RENDER_PATH }}

            - name: Download CI Needed Yak Linux(amd64) Version to operator
              run: wget -q -O './yak' https://oss-qn.yaklang.com/yak/ci/yak_linux_amd64 && chmod +x ./yak

            - name: Upload Multi-Platform Render Zip
              run: |
                  bucket="yaklang"
                  array=("irify" "irifyee")
                  for item in "${array[@]}"; do
                    file_name="${item}.zip"
                    echo "Start to upload ${file_name}"
                    ./yak upload-oss -b $bucket --ak ${{ secrets.OSS_KEY_ID }} --sk ${{ secrets.OSS_KEY_SECRET }} -t 5 -f ${{ env.RENDER_PATH }}/${file_name}:/irify/render/${{ env.TAG_VERSION }}/${file_name}
                  done

            - name: Update OSS latest file
              run: echo ${{ env.TAG_VERSION }} > ./version.txt
            - name: Update OSS latest file
              run: ./yak upload-oss -b "yaklang" --ak ${{ secrets.OSS_KEY_ID }} --sk ${{ secrets.OSS_KEY_SECRET }} -t 5 -f 'version.txt:/irify/render/version.txt'
